openapi: 3.0.1
info:
  title: Higia
  version: 1.0.0

servers:
  - url: /api

paths:
  /exams:
    get:
      tags:
        - Exams
      summary: returns a list of scheduled exams.
      responses:
        '200':
          $ref: '#/components/responses/ResponseOK'
        '500':
          $ref: '#/components/responses/ResponseInternalServerError'
      security:
        - basic: [ ]

    post:
      tags:
        - Exams
      summary: Schedule a new exam.
      requestBody:
        content:
          application/json:
            schema:
              properties:
                patient_identifier:
                  type: string
                  description: Patient identifier(CPF).
                exam_type:
                  type: string
                  description: Exam name.
                exam_local:
                  type: string
                  description: Exam local.
                exam_date:
                  type: string
                  description: Exam date(dd/mm/yyyy).
                validity:
                  type: string
                  description: Exam validity(dd/mm/yyyy).
      responses:
        '201':
          $ref: '#/components/responses/ResponseCreated'
        '400':
          $ref: '#/components/responses/ResponseBadRequest'
        '401':
          $ref: '#/components/responses/ResponseUnauthorized'
        '500':
          $ref: '#/components/responses/ResponseInternalServerError'
      security:
        - basic: [ ]
  /exams/{exam_id}:
    put:
      tags:
        - Exams
      summary: Edit a scheduled exam data.
      parameters:
        - in: path
          name: exam_id
          description: Exam Id.
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              properties:
                patient_identifier:
                  type: string
                  description: Patient identifier(CPF).
                exam_type:
                  type: string
                  description: Exam name.
                exam_local:
                  type: string
                  description: Exam local.
                exam_date:
                  type: string
                  format: date
                  description: Exam date(yyyy-mm-dd).
                validity:
                  type: string
                  format: date
                  description: Exam validity(yyyy-mm-dd).
                result:
                  type: string
                  description: Exam result.
      responses:
        '200':
          $ref: '#/components/responses/ResponseOK'
        '401':
          $ref: '#/components/responses/ResponseUnauthorized'
        '404':
          $ref: '#/components/responses/ResponseNotFound'
        '500':
          $ref: '#/components/responses/ResponseInternalServerError'
      security:
        - basic: [ ]
    delete:
      tags:
        - Exams
      summary: Delete a scheduled exam.
      parameters:
        - in: path
          name: role_name
          description: Name of created role.
          required: true
          schema:
            type: string
      responses:
        '200':
          $ref: '#/components/responses/ResponseOK'
        '401':
          $ref: '#/components/responses/ResponseUnauthorized'
        '404':
          $ref: '#/components/responses/ResponseNotFound'
        '500':
          $ref: '#/components/responses/ResponseInternalServerError'
      security:
        - basic: [ ]
  /roles:
    get:
      tags:
        - Roles
      summary: Retrieve registered roles.
      responses:
        '200':
          $ref: '#/components/responses/ResponseOK'
        '500':
          $ref: '#/components/responses/ResponseInternalServerError'
      security:
        - basic: [ ]

    post:
      tags:
        - Roles
      summary: Create a new role.
      requestBody:
        content:
          application/json:
            schema:
              properties:
                role_name:
                  type: string
                  description: Role name.
      responses:
        '201':
          $ref: '#/components/responses/ResponseCreated'
        '400':
          $ref: '#/components/responses/ResponseBadRequest'
        '401':
          $ref: '#/components/responses/ResponseUnauthorized'
        '500':
          $ref: '#/components/responses/ResponseInternalServerError'
      security:
        - basic: []
  /roles/{role_name}:
    delete:
      tags:
        - Roles
      summary: Delete a created role by name.
      parameters:
        - in: path
          name: role_name
          description: Name of created role.
          required: true
          schema:
            type: string
      responses:
        '200':
          $ref: '#/components/responses/ResponseOK'
        '401':
          $ref: '#/components/responses/ResponseUnauthorized'
        '404':
          $ref: '#/components/responses/ResponseNotFound'
        '500':
          $ref: '#/components/responses/ResponseInternalServerError'
      security:
        - basic: [ ]

  /settings:
    get:
      tags:
        - Settings
      summary: Retrieve system settings.
      responses:
        '200':
          description: OK
      security:
        - basic: [ ]
    post:
      tags:
        - Settings
      summary: Update system configuration.
      requestBody:
        content:
          application/json:
            schema:
              properties:
                lockout:
                  type: boolean
                  description: Enable/Disable intruder lockout.
                lockout_tries:
                  type: integer
                  description: Number of tries until block.
                lockout_time:
                  type: integer
                  description: Block time(in hours).
                log_level:
                  type: string
                  description: Log level.
                password_length:
                  type: integer
                  description: Password length(total).
                password_numbers:
                  type: integer
                  description: Numbers length.
                password_letters:
                  type: integer
                  description: Letters length.
                password_caps:
                  type: integer
                  description: High letters length.
                password_lower:
                  type: integer
                  description: Low letters length.
                password_special:
                  type: integer
                  description: Special chars length.
      responses:
        '201':
          $ref: '#/components/responses/ResponseCreated'
        '400':
          $ref: '#/components/responses/ResponseBadRequest'
        '401':
          $ref: '#/components/responses/ResponseUnauthorized'
        '500':
          $ref: '#/components/responses/ResponseInternalServerError'
      security:
        - basic: [ ]
  /testing:
    get:
      tags:
        - Testing
      summary: Create models in testing env.
      responses:
        '200':
          $ref: '#/components/responses/ResponseOK'
        '500':
          $ref: '#/components/responses/ResponseInternalServerError'
      security:
        - basic: [ ]

  /users:
    get:
      tags:
        - Users
      summary: Retrieve registered users.
      responses:
        '200':
          $ref: '#/components/responses/ResponseOK'
        '500':
          $ref: '#/components/responses/ResponseInternalServerError'
      security:
        - basic: [ ]
    post:
      tags:
        - Users
      summary: Create a new User.
      requestBody:
        content:
          application/json:
            schema:
              properties:
                identifier:
                  type: string
                  description: User identifier(CPF).
                email:
                  type: string
                  description: User email.
                first_name:
                  type: string
                  description: User's first name.
                last_name:
                  type: string
                  description: User's last name.
                password:
                  type: string
                  description: User password.
                cep:
                  type: string
                  description: CEP for identify localization.
                phone:
                  type: string
                  description: User's cellphone.
                roles:
                  type: string
                  description: User's privilege role.
      responses:
        '201':
          $ref: '#/components/responses/ResponseCreated'
        '400':
          $ref: '#/components/responses/ResponseBadRequest'
        '401':
          $ref: '#/components/responses/ResponseUnauthorized'
        '500':
          $ref: '#/components/responses/ResponseInternalServerError'
      security:
        - basic: [ ]
  /users/{identifier}:
    put:
      tags:
        - Users
      summary: Update user data.
      parameters:
        - in: path
          name: identifier
          description: User identifier(CPF).
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              properties:
                identifier:
                  type: string
                  description: User identifier(CPF).
                email:
                  type: string
                  description: User email.
                first_name:
                  type: string
                  description: User's first name.
                last_name:
                  type: string
                  description: User's last name.
                password:
                  type: string
                  description: User password.
                cep:
                  type: string
                  description: CEP for identify localization.
                phone:
                  type: string
                  description: User's cellphone.
      responses:
        '200':
          $ref: '#/components/responses/ResponseOK'
        '401':
          $ref: '#/components/responses/ResponseUnauthorized'
        '404':
          $ref: '#/components/responses/ResponseNotFound'
        '500':
          $ref: '#/components/responses/ResponseInternalServerError'
      security:
        - basic: [ ]
    delete:
      tags:
        - Users
      summary: Delete a created user by identifier.
      parameters:
        - in: path
          name: identifier
          description: User identifier(CPF).
          required: true
          schema:
            type: string
      responses:
        '200':
          $ref: '#/components/responses/ResponseOK'
        '401':
          $ref: '#/components/responses/ResponseUnauthorized'
        '404':
          $ref: '#/components/responses/ResponseNotFound'
        '500':
          $ref: '#/components/responses/ResponseInternalServerError'
      security:
        - basic: [ ]


components:
  securitySchemes:
    basic:
      type: http
      scheme: basic
    basic_client:
      type: http
      scheme: basic
    ClientId:
      type: apiKey
      in: header
      name: client-id
    AccessKey:
      type: apiKey
      in: header
      name: client-access-key

  schemas:
    Success:
      description: Response Message with Success case fields.
      type: object
    Error:
      description: Response Message with error fields.
      type: object

  responses:
    ResponseOK:
      description: Default success response for 200 status code.
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/Success'
    ResponseCreated:
      description: Default success response for 201 status code.
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/Success'
    ResponseBadRequest:
      description: Default error response for 400 status code.
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/Error'
    ResponseUnauthorized:
      description: Default error response for 401 status code.
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/Error'
    ResponseForbidden:
      description: Default error response for 403 status code.
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/Error'
    ResponseNotFound:
      description: Default error response for 404 status code.
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/Error'
    ResponseMethodNotAllowed:
      description: Default error response for 405 status code.
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/Error'
    ResponseConflict:
      description: Default error response for 409 status code.
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/Error'
    ResponseInternalServerError:
      description: Default error response for 500 status code.
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/Error'

