"""empty message

Revision ID: 3656dfa14746
Revises: ab6e31f310db
Create Date: 2023-06-13 21:36:08.728326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3656dfa14746'
down_revision = 'ab6e31f310db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('password_length', sa.Integer(), nullable=True),
    sa.Column('password_numbers', sa.Integer(), nullable=True),
    sa.Column('password_letters', sa.Integer(), nullable=True),
    sa.Column('password_caps', sa.Integer(), nullable=True),
    sa.Column('password_lower', sa.Integer(), nullable=True),
    sa.Column('password_special', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('password_caps'),
    sa.UniqueConstraint('password_length'),
    sa.UniqueConstraint('password_letters'),
    sa.UniqueConstraint('password_lower'),
    sa.UniqueConstraint('password_numbers'),
    sa.UniqueConstraint('password_special')
    )
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_settings_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settings_created_at'))

    op.drop_table('settings')
    # ### end Alembic commands ###
