"""empty message

Revision ID: 536028817dc9
Revises: 
Create Date: 2023-10-25 18:06:49.872643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '536028817dc9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collaborators',
    sa.Column('code', sa.String(length=12), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('password_hash', sa.String(length=500), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('last_password_change', sa.DateTime(), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=True),
    sa.Column('blocked_until', sa.DateTime(), nullable=True),
    sa.Column('login_tries', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('collaborators', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collaborators_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_collaborators_id'), ['id'], unique=False)

    op.create_table('patients',
    sa.Column('identifier', sa.String(length=11), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=13), nullable=True),
    sa.Column('cep', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('password_hash', sa.String(length=500), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('last_password_change', sa.DateTime(), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=True),
    sa.Column('blocked_until', sa.DateTime(), nullable=True),
    sa.Column('login_tries', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patients_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_identifier'), ['identifier'], unique=True)

    op.create_table('roles',
    sa.Column('role_name', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_name')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_id'), ['id'], unique=False)

    op.create_table('settings',
    sa.Column('password_length', sa.Integer(), nullable=True),
    sa.Column('password_numbers', sa.Integer(), nullable=True),
    sa.Column('password_letters', sa.Integer(), nullable=True),
    sa.Column('password_caps', sa.Integer(), nullable=True),
    sa.Column('password_lower', sa.Integer(), nullable=True),
    sa.Column('password_special', sa.Integer(), nullable=True),
    sa.Column('log_level', sa.String(length=100), nullable=True),
    sa.Column('lockout', sa.Boolean(), nullable=True),
    sa.Column('lockout_tries', sa.Integer(), nullable=True),
    sa.Column('lockout_time', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_settings_id'), ['id'], unique=False)

    op.create_table('collaborators_roles',
    sa.Column('collaborators_id', sa.String(length=50), nullable=False),
    sa.Column('role_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['collaborators_id'], ['collaborators.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], )
    )
    op.create_table('exams',
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('exam_type', sa.String(length=100), nullable=False),
    sa.Column('exam_local', sa.String(length=100), nullable=False),
    sa.Column('exam_date', sa.DateTime(), nullable=False),
    sa.Column('validity', sa.DateTime(), nullable=True),
    sa.Column('patient', sa.String(length=50), nullable=True),
    sa.Column('patient_name', sa.String(length=100), nullable=False),
    sa.Column('patient_identifier', sa.String(length=11), nullable=False),
    sa.Column('doctor', sa.String(length=50), nullable=True),
    sa.Column('doctor_name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctor'], ['collaborators.id'], ),
    sa.ForeignKeyConstraint(['patient'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exams_id'), ['id'], unique=False)

    op.create_table('patient_roles',
    sa.Column('patient_id', sa.String(length=50), nullable=False),
    sa.Column('role_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], )
    )
    op.create_table('scheduling',
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('local', sa.Text(), nullable=False),
    sa.Column('specialty', sa.String(length=100), nullable=False),
    sa.Column('appointment_day', sa.DateTime(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('return_date', sa.DateTime(), nullable=True),
    sa.Column('patient', sa.String(length=50), nullable=True),
    sa.Column('patient_name', sa.String(length=100), nullable=False),
    sa.Column('patient_identifier', sa.String(length=11), nullable=False),
    sa.Column('doctor', sa.String(length=50), nullable=True),
    sa.Column('doctor_name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctor'], ['collaborators.id'], ),
    sa.ForeignKeyConstraint(['patient'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scheduling', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scheduling_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduling', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheduling_id'))

    op.drop_table('scheduling')
    op.drop_table('patient_roles')
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exams_id'))

    op.drop_table('exams')
    op.drop_table('collaborators_roles')
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settings_id'))

    op.drop_table('settings')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_id'))

    op.drop_table('roles')
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patients_identifier'))
        batch_op.drop_index(batch_op.f('ix_patients_id'))

    op.drop_table('patients')
    with op.batch_alter_table('collaborators', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collaborators_id'))
        batch_op.drop_index(batch_op.f('ix_collaborators_code'))

    op.drop_table('collaborators')
    # ### end Alembic commands ###
