"""empty message

Revision ID: 5537cba4df50
Revises: 6b76ea56f80e
Create Date: 2023-10-24 16:21:28.911087

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5537cba4df50'
down_revision = '6b76ea56f80e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=100), nullable=False))
        batch_op.drop_column('first_name')
        batch_op.drop_column('last_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', mysql.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('first_name', mysql.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
