"""empty message

Revision ID: 74aa4ad62e60
Revises: a11ba5db748f
Create Date: 2023-07-06 18:00:18.026041

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '74aa4ad62e60'
down_revision = 'a11ba5db748f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('doctor_id', sa.String(length=50), nullable=True))
        batch_op.drop_constraint('exams_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('exams_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['patient_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['doctor_id'], ['id'])
        batch_op.drop_column('patient')
        batch_op.drop_column('doctor')

    with op.batch_alter_table('scheduling', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('doctor_id', sa.String(length=50), nullable=True))
        batch_op.drop_constraint('scheduling_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('scheduling_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['patient_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['doctor_id'], ['id'])
        batch_op.drop_column('patient')
        batch_op.drop_column('doctor')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduling', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doctor', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('patient', mysql.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('scheduling_ibfk_2', 'users', ['patient'], ['id'])
        batch_op.create_foreign_key('scheduling_ibfk_1', 'users', ['doctor'], ['id'])
        batch_op.drop_column('doctor_id')
        batch_op.drop_column('patient_id')

    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doctor', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('patient', mysql.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('exams_ibfk_2', 'users', ['patient'], ['id'])
        batch_op.create_foreign_key('exams_ibfk_1', 'users', ['doctor'], ['id'])
        batch_op.drop_column('doctor_id')
        batch_op.drop_column('patient_id')

    # ### end Alembic commands ###
