"""empty message

Revision ID: 9a5e8380ea9d
Revises: c7aa547113f5
Create Date: 2023-07-11 15:39:07.159068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a5e8380ea9d'
down_revision = 'c7aa547113f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('patient_identifier', sa.String(length=11), nullable=False))
        batch_op.add_column(sa.Column('doctor_name', sa.String(length=100), nullable=False))

    with op.batch_alter_table('scheduling', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('patient_identifier', sa.String(length=11), nullable=False))
        batch_op.add_column(sa.Column('doctor_name', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduling', schema=None) as batch_op:
        batch_op.drop_column('doctor_name')
        batch_op.drop_column('patient_identifier')
        batch_op.drop_column('patient_name')

    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.drop_column('doctor_name')
        batch_op.drop_column('patient_identifier')
        batch_op.drop_column('patient_name')

    # ### end Alembic commands ###
