"""empty message

Revision ID: a11ba5db748f
Revises: d64225acbcf4
Create Date: 2023-06-30 17:07:17.506402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a11ba5db748f'
down_revision = 'd64225acbcf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exams',
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('exam_type', sa.String(length=100), nullable=False),
    sa.Column('exam_local', sa.String(length=100), nullable=False),
    sa.Column('exam_date', sa.DateTime(), nullable=False),
    sa.Column('validity', sa.DateTime(), nullable=True),
    sa.Column('patient', sa.String(length=50), nullable=True),
    sa.Column('doctor', sa.String(length=50), nullable=True),
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctor'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exams_created_at'), ['created_at'], unique=False)

    op.create_table('scheduling',
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('local', sa.Text(), nullable=False),
    sa.Column('specialty', sa.String(length=100), nullable=False),
    sa.Column('appointment_day', sa.DateTime(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('return_date', sa.DateTime(), nullable=True),
    sa.Column('patient', sa.String(length=50), nullable=True),
    sa.Column('doctor', sa.String(length=50), nullable=True),
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctor'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scheduling', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scheduling_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduling', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheduling_created_at'))

    op.drop_table('scheduling')
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exams_created_at'))

    op.drop_table('exams')
    # ### end Alembic commands ###
