"""empty message

Revision ID: bb2dcb43cb4c
Revises: 3656dfa14746
Create Date: 2023-06-27 17:55:26.436445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb2dcb43cb4c'
down_revision = '3656dfa14746'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('log_level', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('lockout', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('lockout_tries', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('lockout_time', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('lockout_time')
        batch_op.drop_column('lockout_tries')
        batch_op.drop_column('lockout')
        batch_op.drop_column('log_level')

    # ### end Alembic commands ###
