"""empty message

Revision ID: c7aa547113f5
Revises: 74aa4ad62e60
Create Date: 2023-07-10 13:12:53.139880

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c7aa547113f5'
down_revision = '74aa4ad62e60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('doctor', sa.String(length=50), nullable=True))
        batch_op.drop_constraint('exams_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('exams_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['doctor'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['patient'], ['id'])
        batch_op.drop_column('patient_id')
        batch_op.drop_column('doctor_id')

    with op.batch_alter_table('scheduling', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('doctor', sa.String(length=50), nullable=True))
        batch_op.drop_constraint('scheduling_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('scheduling_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['doctor'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['patient'], ['id'])
        batch_op.drop_column('patient_id')
        batch_op.drop_column('doctor_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduling', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doctor_id', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('patient_id', mysql.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('scheduling_ibfk_2', 'users', ['doctor_id'], ['id'])
        batch_op.create_foreign_key('scheduling_ibfk_1', 'users', ['patient_id'], ['id'])
        batch_op.drop_column('doctor')
        batch_op.drop_column('patient')

    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doctor_id', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('patient_id', mysql.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('exams_ibfk_2', 'users', ['doctor_id'], ['id'])
        batch_op.create_foreign_key('exams_ibfk_1', 'users', ['patient_id'], ['id'])
        batch_op.drop_column('doctor')
        batch_op.drop_column('patient')

    # ### end Alembic commands ###
