"""empty message

Revision ID: d64225acbcf4
Revises: bb2dcb43cb4c
Create Date: 2023-06-28 11:21:45.430434

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd64225acbcf4'
down_revision = 'bb2dcb43cb4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.alter_column('lockout_time',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.drop_index('password_caps')
        batch_op.drop_index('password_length')
        batch_op.drop_index('password_letters')
        batch_op.drop_index('password_lower')
        batch_op.drop_index('password_numbers')
        batch_op.drop_index('password_special')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.create_index('password_special', ['password_special'], unique=False)
        batch_op.create_index('password_numbers', ['password_numbers'], unique=False)
        batch_op.create_index('password_lower', ['password_lower'], unique=False)
        batch_op.create_index('password_letters', ['password_letters'], unique=False)
        batch_op.create_index('password_length', ['password_length'], unique=False)
        batch_op.create_index('password_caps', ['password_caps'], unique=False)
        batch_op.alter_column('lockout_time',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    # ### end Alembic commands ###
